# NOTE: update this with your service name
service: location-record-poc

package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  
  environment:
    tableName: process.env.TABLE_NAME

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  create:
    handler: src/createLocation.main
    events:
      - http:
          path: create-location
          method: post
          cors: true
  get:
    handler: src/getLocation.main
    events:
      - http:
          path: get-location
          method: post
          cors: true